---
- name: Ansible playbook to run httpd with Notify & handlers
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: install httpd on RHEL Servers
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"
      notify: start httpd services
    - name: install httpd on DEBIAN Servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
    - copy:
        src: /home/ansadmin/playbook/index.html
        dest: /var/www/html

  handlers:
    - name: start httpd services
      service:
        name: httpd
        state: started

Notify and handlers: If we run a playbook created to install and run httpd service then every time we playbook for fresh install or change in configuration then,
                     it will start httpd service resulting into outage. To avoid it we may introduce notify and handlers so that the handler will execute only
                     when notified.

